### PR TITLE
fixed building with ubuntu 20.10 c++ 10.2.0

### PR DESCRIPTION
**Pull request by h4sh5**
Fix for issue https://github.com/GrammaTech/gtirb-pprinter/issues/4

### CODE REVIEW

**Comment by iconmaster5326** [comment]
I see you have changed some Capstone constants there. What version of Capstone are you using?

**Comment by KipHamiltons** [comment]
I had this issue (#4) on Arch too.
GCC/G++: 10.2.0
Capstone: 4.0.2-3

This patch fixed it for me too.

**Comment by iconmaster5326** [comment]
@KipHamiltons, I find that interesting since all the relevant changes are gated behind a conditional include that only triggers when the version of Capstone you use is 5 or above. Where did you install Capstone from?

**Comment by KipHamiltons** [comment]
At first I tried installing from the current [latest source](https://github.com/aquynh/capstone), and had that same issue.
While troubleshooting the issue (before checking this repo and finding the issue/patch), I removed that installation, and got capstone from the [arch community repository](https://archlinux.org/packages/community/x86_64/capstone/).

**Comment by iconmaster5326** [comment]
We now require you use an internal build of Capstone to make this project, which can be found [here](https://github.com/GrammaTech/capstone/tree/next). Note that we're using the `next` branch, not `main`! Can you try using that and seeing if gtirb-pprinter compiles without these modifications?

**Comment by KipHamiltons** [comment]
I just built in a fresh arch container without issues.

**Comment by iconmaster5326** [comment]
Great to hear! Closing this PR now, since it is no longer necessary.

We're working on getting our changes merged back into Capstone so we can eventually use the versions in package repositories, but for now we'll have to stick with using our fork.

**Pull request closed without merging**
